name: shell commands 

on: [push]
  

jobs:

    run-shell-commands:
      runs-on: ubunto-latest
      steps:
        - name: string
          run: echo"welcom to devopshint"
        - name: multime script
          run: |
          node -v
          npm -v 

    